# API_HOST = 'http://188.166.183.205/publiccamera/api/index.php/v1'
API_HOST = 'http://188.166.183.205/publiccamera/api/index.php/v1'
PROJECTS = '/projects'
SEARCH_BY_PROJECT = '/floors/search'
SEARCH_BY_FLOOR = '/nodes/search'
ALL_FLOORS_DATA = '/floor-datas'
LIST_BY_FLOOR_AND_LABEL = '/floor-datas/list-by-floor-and-label'
